services:
  - type: web
    name: dravacard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    # Redirect all requests to index.html for SPA routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
